In [ ]:
## INITIATING NUMPY PACKAGE

In [36]:
import numpy as np

In [38]:
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [40]:
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [42]:
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [44]:
grades.ndim

1

In [34]:
## Use numpy functions to calculate the mean, median, and standard deviation of the grades.

In [54]:
np.mean(grades)

87.5

In [56]:
np.median(grades)

88.5

In [58]:
np.std(grades)

6.591661399070799

In [60]:
##Use numpy function to find the maximum and minimum of the grades.

In [62]:
np.min(grades)

75

In [64]:
np.max(grades)

98

In [66]:
## Use numpy function to sort the grades in ascending order.

In [70]:
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [72]:
## Use numpy function to find the index of the highest grade in the array.

In [74]:
np.argmax(grades)

7

In [76]:
## Use numpy function to count the number of students who scored above 90.

In [78]:
np.sum(grades > 90)

3

In [80]:
## Use numpy function to calculate the percentage of students who scored above 90.

In [83]:
## Use numpy function to calculate the percentage of students who scored below 75.

In [85]:
np.sum(grades < 75)

0

In [89]:
## Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".

In [95]:
high_performers = grades[grades > 90]

In [97]:
high_performers

array([92, 95, 98])

In [99]:
## Create a new array called "passing_grades" that contains all the grades above 75.

In [101]:
passing_grades = grades[grades > 75]

In [103]:
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])